config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  post 'import' => 'application#import'
  post 'start' => 'application#start'
  get 'start' => 'application#start'
  get 'bycat' => 'products#bycat'
  post 'show' => 'products#index'

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  def self.import(file)
    # Delete all existing Products
    ActiveRecord::Base.connection.execute("Delete from products;")
    
    # Reset the sequence
    ActiveRecord::Base.connection.execute("delete from sqlite_sequence where name='products';")
     
    CSV.foreach(file.path, headers: true) do |row|
      rowhash = row.to_hash
      rowhash['ProductName'] = rowhash.delete('Product Name')
      Product.create! rowhash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def import
      Product.import(params[:file])
      flash[:success] = "Import Complete"
      redirect_to '/products'
    end
    def start
    end
    def bycat
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:ProductID, :Category, :ProductName, :Price)
    end

    def import
      Product.import(params[:file])
    end

    def bycat
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/bycat.html.erb
<h1>Product Name</h1>
<br><br>
<% prdcat = Product.paginate(:page => params[:page], :per_page => 5).where({ :Category => params[:Category]}).order("ProductName") %>
<% prdcat.each do | prd | %>
  <h1><%= link_to prd.ProductName, products_path + "/" + prd.id.to_s %> </h1>
<% end %>
    <div class="store_pagination">
      <%= will_paginate prdcat %>
    </div>

app/views/application/import.html.erb
Hello

app/views/application/start.html.erb
<h1>Upload Product Catalog</h1>
<%= form_tag import_path, multipart: true do %>
  <%= file_field_tag :file , class: "btn btn-lg btn-primary", width: "100" %>
  <br>
  <%= submit_tag "Trigger Import", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Online Store App developed by Hardik Joshi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   root_path %></li>
      <li><%= link_to "Contact", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Welcome to Online Store", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Product Categories",    root_path %></li>
        <li><%= link_to "Import Products",    start_path %></li>
        <li><%= link_to "Log in", root_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
     </div>
  </body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ProductID %><br>
    <%= f.text_field :ProductID %>
  </div>
  <div class="field">
    <%= f.label :Category %><br>
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :ProductName %><br>
    <%= f.text_field :ProductName %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.number_field :Price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.1.erb
<p id="notice"><%= notice %></p>

<% @products.distinct(:Category).pluck(:Category).sort.each do |category| %>
   <h1> <%= category %> </h1>
<% end %>

<h1>Listing Products</h1>


<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th>Category</th>
      <th>Productname</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.ProductID %></td>
        <td><%= product.Category %></td>
        <td><%= product.ProductName %></td>
        <td><%= product.Price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Categories</h1>
<br>
<br>
<% if @products.count == 0 %>
    <p>Product Categories not loaded. Click Link below for upload page</p>
    <h1><%= link_to "Import Products",    start_path %></h1>
<% end %>
<% @products.distinct(:Category).pluck(:Category).sort.each do |category| %>
   <h1><%= link_to category.to_s, bycat_path(:Category => category) %></h1>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Details</h1>

<p .uneditable-input>
  <strong>Productid:</strong>
  <%= @product.ProductID %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.Category %>
</p>

<p>
  <strong>Productname:</strong>
  <%= @product.ProductName %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.Price %>
</p>